### ISSUE TITLE
Used with Ng-For

### ISSUE THREAD

**Issue by Faris-AH** [Oneia/read-more-angular2#1]
How can i use with ng-for?

**Comment by Faris-AH** [comment]
Fixed by giving dynamic id 
Ref
https://stackoverflow.com/questions/36051195/give-dynamic-id-angular2-binds

**Comment by raghuaje** [comment]
not working with dynamic id

**Comment by raghuaje** [comment]
<div class="row col-sm-12 col-xs-12">
          <h4><strong>{{project.title}}, {{project.location}}</strong></h4>
          <h5>{{project.info}}</h5>
          <h6 #textContent id="read-more {{ i }} ">Amaneties: {{project.amaneties}} </h6>
          <div class="read-more-link">
            <a readMore [readMore-length]="100" [readMore-element]="textContent">
	 	          <span class="less">Less <i class="fa fa-angle-left" aria-hidden="true"></i></span>
	 	          <span class="more">More <i class="fa fa-angle-right" aria-hidden="true"></i></span>
	           </a>
          </div>




doing this and only first element is hide and seek when click on any other component

**Comment by raghuaje** [comment]
`<div class="row col-sm-12 col-xs-12">
      <h4><strong>{{project.title}}, {{project.location}}</strong></h4>
      <h5>{{project.info}}</h5>
      <h6 #textContent id="read-more {{ i }} ">Amaneties: {{project.amaneties}} </h6>
      <div class="read-more-link">
        <a readMore [readMore-length]="100" [readMore-element]="textContent">
              <span class="less">Less <i class="fa fa-angle-left" aria-hidden="true"></i></span>
              <span class="more">More <i class="fa fa-angle-right" aria-hidden="true"></i></span>
           </a>
      </div>`


Not working
