### ISSUE TITLE
Not working with ngFor

### ISSUE THREAD

**Issue by raghuaje** [Oneia/read-more-angular2#2]
https://stackoverflow.com/questions/44566017/read-more-for-angular-2-with-ngfor

see my code not working with ngFor

**Comment by Oneia** [comment]
You need to define variable "i". You should add "let i = index;" in *ngFor string. It should look like *ngFor="let project of projects | filter: location; let i = index";

**Comment by raghuaje** [comment]
<div class="project col-sm-2 col-xs-12 rapro" *ngFor="let project of projects | filter: location; let i = index";>
      <div class="col-sm-12 col-xs-12" style="padding:0px;">
          <img [src]="project.avatar" class="img-responsive">
        </div>
        <div class="row col-sm-12 col-xs-12" >
          <h4><strong>{{project.title}}, {{project.location}}</strong></h4>
          <h5>{{project.info}}</h5>
          <h6 #textContent id="read-more {{i}}">Amaneties: {{project.amaneties}} </h6>
          <div class="read-more-link">
            <a readMore [readMore-length]="100" [readMore-element]="textContent">
	 	          <span class="more">More <i class="fa fa-angle-right" aria-hidden="true"></i></span>
	           </a>
          </div>
          <h6>Site Address: {{project.address}}</h6>
          
        </div>



Not working with this also

caused by: Failed to execute 'setAttribute' on 'Element': ';' is not a valid attribute name.↵    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6688:33)↵    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:83062:16)↵    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:83127:16)↵    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:84431:16)↵    at View_ProjectComponent1.webpackJsonp.../../../core/src/linker/view.js.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:85825:23)↵    at View_ProjectComponent1.webpackJsonp.../../../core/src/linker/view.js.DebugAppView.create (http://localhost:4200/vendor.bundle.js:85725:18)↵    at TemplateRef_.webpackJsonp.../../../core/src/linker/template_ref.js.TemplateRef_.createEmbeddedView (http://localhost:4200/vendor.bundle.js:85134:14)↵    at ViewContainerRef_.webpackJsonp.../../../core/src/linker/view_container_ref.js.ViewContainerRef_.createEmbeddedView (http://localhost:4200/vendor.bundle.js:86290:52)↵    at http://localhost:4200/vendor.bundle.js:36434:66↵    at DefaultIterableDiffer.webpackJsonp.../../../core/src/change_detection/differs/default_iterable_differ.js.DefaultIterableDiffer.forEachOperation (http://localhost:4200/vendor.bundle.js:78348:17)↵    at NgFor.webpackJsonp.../../../common/src/directives/ng_for.js.NgFor._applyChanges (http://localhost:4200/vendor.bundle.js:36432:17)↵    at NgFor.webpackJsonp.../../../common/src/directives/ng_for.js.NgFor.ngDoCheck (http://localhost:4200/vendor.bundle.js:36422:22)↵    at Wrapper_NgFor.ngDoCheck (/CommonModule/NgFor/wrapper.ngfactory.js:53:18)↵    at CompiledTemplate.proxyViewClass.View_ProjectComponent0.detectChangesInternal (/AppModule/ProjectComponent/component.ngfactory.js:419:20)↵    at CompiledTemplate.proxyViewClass.webpackJsonp.../../../core/src/linker/view.js.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:85600:14)"
zoneAwareStack

"Error: Error in ./ProjectComponent class ProjectComponent - inline template:17:6 caused by: Failed to execute 'setAttribute' on 'Element': ';' is not a valid attribute name.↵    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6688:33)↵
