### ISSUE TITLE
Not working with ngFor

### ISSUE THREAD

**Issue by raghuaje** [Oneia/read-more-angular2#3]
`<div class="project col-sm-2 col-xs-12 rapro" *ngFor="let project of projects | filter: location">`
        `<div class="col-sm-12 col-xs-12" style="padding:0px;">`
         ` <img [src]="project.avatar" class="img-responsive">`
        `</div>`
`<div class="row col-sm-12 col-xs-12">`
      `<h4><strong>{{project.title}}, {{project.location}}</strong></h4>`
      `<h5>{{project.info}}</h5>`
     ` <h6 #textContent id="read-more {{ i }} ">Amaneties: {{project.amaneties}} </h6>`
      `<div class="read-more-link">`
       ` <a readMore [readMore-length]="100" [readMore-element]="textContent">`
           `   <span class="less">Less <i class="fa fa-angle-left" aria-hidden="true"></i></span>`
              `<span class="more">More <i class="fa fa-angle-right" aria-hidden="true"></i></span>`
          ` </a>`
      `</div>`
`</div>`

this is only changing data on first element if i click on more for another element it effect on first element only .

**Comment by Oneia** [comment]
You need to define variable "i". You should add "let i = index;" in *ngFor string. It should look like *ngFor="let project of projects | filter: location; let i = index";

**Comment by raghuaje** [comment]
Not Working with this also .

**Comment by artemmozharovandersen** [comment]
share your code then

**Comment by Oneia** [comment]
share your code then

**Comment by raghuaje** [comment]
I sent you mail on i.blanar@andersenlab.com please check it 
Thank you
