### ISSUE TITLE
Unable to use with variable

### ISSUE THREAD

**Issue by tomsfernandez** [Oneia/read-more-angular2#5]
When using variables, it doesn't work
<div style="display: block;font-size: small">
        <p #textContent id="read-more">
          {{snippet?.description}}
        </p>

        <div *ngIf="snippetDescription.length >= 100" class="read-more-link">
          <a readMore [readMore-length]="100" [readMore-element]="textContent">
            <span class="less">Less <i class="fa fa-angle-right" aria-hidden="true"></i></span>
            <span class="more">More <i class="fa fa-angle-right" aria-hidden="true"></i></span>
          </a>
        </div>
      </div>

In this case the text in the variable snippet.description does not show. It also doesn't show if there isn't the '?'

**Comment by Oneia** [comment]
could you provide your full code of the template?
